from __future__ import annotations

from collections import Counter, defaultdict
from datetime import datetime
import re
from typing import Any, Dict, Iterable, List, Optional, Tuple
from urllib.parse import urlparse

from .dingtalk_ai_table import status_name
from .gbss_report import build_report_data, truncate_text


SECTION_TITLES = {
    "Finance": "Finance, Payments & Banking",
    "Contact Center": "Contact Center with Voice AI",
    "News": "Other Relevant Headlines",
}

FINANCE_HINTS = (
    "adyen", "airwallex", "alipay", "antom", "bank", "banking", "checkout",
    "cross-border", "fintech", "lianlian", "mastercard", "payment", "paypal",
    "stripe", "visa", "wise", "xtransfer",
)

CONTACT_CENTER_HINTS = (
    "agentforce", "amazon connect", "call center", "contact center",
    "conversational", "cx", "deepgram", "gemini", "sierra", "vapi",
    "voice ai", "zendesk",
)

COMPETITOR_ALIASES = {
    "Antom": ("antom", "ant international", "alipay+"),
    "WorldFirst": ("worldfirst",),
    "Wise": ("wise", "wise business"),
    "Payoneer": ("payoneer",),
    "PingPong": ("pingpong",),
    "XTransfer": ("xtransfer",),
    "Airwallex": ("airwallex",),
    "Revolut": ("revolut",),
    "Stripe": ("stripe",),
    "Adyen": ("adyen",),
    "PayPal": ("paypal",),
    "Visa": ("visa",),
    "Mastercard": ("mastercard",),
    "Salesforce": ("salesforce", "agentforce"),
    "Amazon Connect": ("amazon connect",),
    "Deepgram": ("deepgram",),
    "Vapi": ("vapi",),
    "Sierra.ai": ("sierra.ai", "sierra ai"),
    "Zendesk": ("zendesk",),
    "Twilio": ("twilio",),
    "Genesys": ("genesys",),
    "NICE": ("nice",),
    "Five9": ("five9",),
    "Talkdesk": ("talkdesk",),
    "Intercom": ("intercom",),
    "OpenAI": ("openai",),
    "Anthropic": ("anthropic",),
    "Microsoft": ("microsoft",),
    "Google": ("google", "gemini"),
}

METRIC_HINTS = (
    "annual report", "arr", "earnings", "ebitda", "gmv", "profit", "q1",
    "q2", "q3", "q4", "revenue", "tpv", "transaction volume", "valuation",
    "volume", "估值", "年报", "收入", "规模", "利润",
)

FUNDING_HINTS = (
    "acquire", "acquisition", "funding", "fundraise", "investment", "ipo",
    "m&a", "merger", "raises", "round", "valuation", "融资", "上市",
    "估值", "收购", "投资",
)

MAX_HEADLINE_WORDS = 18

NOTE = (
    "Note: All the above information was generated by AI and merged with manual verification. "
    "If you have any suggestions or feedback, please feel free to contact Franco at any time."
)

AI_DEADLINE_NOTE = (
    "Note: This report uses AI-assisted public-source screening and includes one or more deadline-fallback items "
    "that were not individually approved before publication. Source links and publish dates are retained for review. "
    "Please contact Franco with corrections or feedback."
)

EXECUTIVE_NOTE = (
    "Methodology: Based on accepted public-source records in News; source links are retained above, "
    "and the generated report is archived in Insights for traceability."
)


def is_accepted_record(record: Dict[str, Any], field_mapping: Dict[str, str]) -> bool:
    return status_name(record.get("fields") or {}, field_mapping) == "已采纳"


def numeric_date(value: Any) -> int:
    if isinstance(value, (int, float)):
        return int(value)
    if isinstance(value, str):
        stripped = value.strip()
        if stripped.isdigit():
            return int(stripped)
        for fmt in ("%Y-%m-%d", "%Y/%m/%d"):
            try:
                return int(datetime.strptime(stripped, fmt).timestamp() * 1000)
            except ValueError:
                continue
    return 0


def record_date(record: Dict[str, Any]) -> int:
    fields = record.get("fields") or {}
    return numeric_date(fields.get("Publish Date")) or numeric_date(fields.get("First Seen At"))


def record_sort_key(record: Dict[str, Any]) -> Tuple[str, int, str]:
    return (
        section_name(record),
        -record_date(record),
        str(record.get("id") or ""),
    )


def source_url(fields: Dict[str, Any]) -> str:
    value = fields.get("Source URL") or {}
    if isinstance(value, dict):
        return str(value.get("link") or value.get("text") or "")
    return str(value or "")


def source_domain(url: str) -> str:
    parsed = urlparse(url)
    return parsed.netloc.lower().removeprefix("www.") or url


def field_text(value: Any) -> str:
    if isinstance(value, dict):
        return str(value.get("name") or value.get("text") or value.get("link") or "")
    if isinstance(value, list):
        return ", ".join(field_text(item) for item in value if field_text(item))
    return str(value or "")


def concise_headline(value: Any) -> str:
    text = str(value or "-").strip()
    if " | " in text:
        parts = [part.strip() for part in text.split(" | ") if part.strip()]
        text = parts[0]
        latin_words = lambda part: re.findall(r"[A-Za-z][A-Za-z0-9+&'-]*", part)
        translated = [part for part in parts[1:] if len(latin_words(part)) >= 5]
        if len(latin_words(text)) < 4 and translated:
            text = max(translated, key=lambda part: len(latin_words(part)))
    words = text.split()
    if len(words) <= MAX_HEADLINE_WORDS:
        return text
    return " ".join(words[:MAX_HEADLINE_WORDS]).rstrip(".,;:") + "..."


def record_text(record: Dict[str, Any]) -> str:
    fields = record.get("fields") or {}
    values = [
        fields.get("Title"),
        fields.get("Title & URL"),
        fields.get("Label"),
        fields.get("Tag"),
        fields.get("Section"),
        fields.get("Source"),
        fields.get("Source Domain"),
        source_url(fields),
    ]
    return " ".join(field_text(value) for value in values).lower()


def label_name(fields: Dict[str, Any]) -> str:
    label = field_text(fields.get("Label") or fields.get("Tag") or "News") or "News"
    translations = {
        "产品": "Product",
        "产品/能力": "Product / Capability",
        "能力": "Capability",
        "融资": "Funding",
        "并购": "M&A",
        "资本/并购": "Capital / M&A",
        "规模/业绩": "Scale / Performance",
        "合作/生态": "Partnership / Ecosystem",
        "监管/合规": "Regulation / Compliance",
        "行业/未归类": "Unclassified",
    }
    return translations.get(label, label)


def record_entities(record: Dict[str, Any]) -> List[str]:
    text = record_text(record)
    names = [
        entity for entity, aliases in COMPETITOR_ALIASES.items()
        if any(alias in text for alias in aliases)
    ]
    return names or ["Other"]


def first_source_link(record: Dict[str, Any]) -> str:
    fields = record.get("fields") or {}
    url = source_url(fields)
    if not url:
        return source_domain(field_text(fields.get("Source") or fields.get("Source Domain")))
    return f"[{source_domain(url)}]({url})"


def is_metric_record(record: Dict[str, Any]) -> bool:
    text = record_text(record)
    return any(hint in text for hint in METRIC_HINTS)


def is_funding_record(record: Dict[str, Any]) -> bool:
    fields = record.get("fields") or {}
    label = label_name(fields).lower()
    text = record_text(record)
    return label in {"funding", "m&a", "earnings"} or any(hint in text for hint in FUNDING_HINTS)


def section_name(record: Dict[str, Any]) -> str:
    fields = record.get("fields") or {}
    section = fields.get("Section")
    if section:
        return str(section)
    text = " ".join([
        str(fields.get("Title") or ""),
        str(fields.get("Title & URL") or ""),
        source_url(fields),
        str(fields.get("Source") or ""),
    ]).lower()
    if any(hint in text for hint in FINANCE_HINTS):
        return "Finance"
    if any(hint in text for hint in CONTACT_CENTER_HINTS):
        return "Contact Center"
    return "News"


def format_date_label(timestamp_ms: int) -> str:
    if not timestamp_ms:
        return ""
    return datetime.fromtimestamp(timestamp_ms / 1000).strftime("%b %d").upper()


def selected_date_range(records: Iterable[Dict[str, Any]], fallback: datetime) -> str:
    dates = [record_date(record) for record in records if record_date(record)]
    if not dates:
        return fallback.strftime("%b %d").upper()
    start = format_date_label(min(dates))
    end = format_date_label(max(dates))
    return start if start == end else f"{start} - {end}"


def ordered_sections(records: Iterable[Dict[str, Any]]) -> List[str]:
    sections: List[str] = []
    for record in records:
        section = section_name(record)
        if section not in sections:
            sections.append(section)
    ordered: List[str] = []
    for preferred in ("Finance", "Contact Center", "News"):
        if preferred in sections:
            ordered.append(preferred)
            sections.remove(preferred)
    return ordered + sections


def sorted_recent_records(records: Iterable[Dict[str, Any]]) -> List[Dict[str, Any]]:
    return sorted(records, key=lambda record: (-record_date(record), str(record.get("id") or "")))


def business_signal(record: Dict[str, Any]) -> str:
    fields = record.get("fields") or {}
    label = label_name(fields)
    headline = concise_headline(fields.get("Title") or fields.get("Title & URL") or "-")
    return f"{label}: {headline}"


def top_entity_records(records: List[Dict[str, Any]], limit: int = 8) -> List[Tuple[str, List[Dict[str, Any]]]]:
    grouped: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for record in sorted_recent_records(records):
        for entity in record_entities(record):
            grouped[entity].append(record)
    ranked = sorted(grouped.items(), key=lambda item: (item[0] == "Other", -len(item[1]), item[0]))
    return ranked[:limit]


def markdown_cell(value: Any) -> str:
    if value is None:
        return "-"
    return str(value).replace("|", "/").replace("\n", " ").strip() or "-"


def markdown_table(headers: List[str], rows: List[List[Any]]) -> List[str]:
    lines = [
        "| " + " | ".join(markdown_cell(header) for header in headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(markdown_cell(value) for value in row) + " |")
    return lines


def report_content_to_document_markdown(content: str) -> str:
    section_titles = {
        "Executive Summary",
        "I. Business Performance and Competitor Moves",
        "I. Business Performance and Competitor Moves / 业务表现与竞对动作",
        "II. Scale, Valuation and Funding Signals",
        "II. Scale, Valuation and Funding Signals / 规模、估值与融资信号",
        "III. Key Developments This Week",
        "III. Key Developments This Week / 本周重点动态",
        "IV. Strategic Analysis",
        "IV. Strategic Analysis / 重点分析",
        "V. Recommended Management Actions",
        "V. Recommended Management Actions / 管理层建议动作",
        "VI. Next 4 Topics Preview",
        "VII. Research Direction",
        "VII. Research Direction / 接下来一段时间的调研方向",
        "1. Executive Summary / 本周关键结论与主题判断",
        "Key Takeaways / 关键结论",
        "2. External Signal Radar / 外部动态雷达",
        "3. Priority News Cards / 本周重点动态卡片",
        "4. GBSS Impact Analysis / GBSS 影响分析",
        "5. Actions, Watchlist & Deep Dive / 行动建议、下周观察与深度分析",
    }
    output: List[str] = []
    for index, line in enumerate(content.splitlines()):
        stripped = line.strip()
        if index == 0 and stripped:
            output.append(f"# {stripped}")
        elif stripped in section_titles:
            output.append(f"## {stripped}")
        elif stripped == "--------------------------":
            output.append("---")
        else:
            output.append(line)
    return "\n".join(output).strip() + "\n"


def _content_value(content: str, prefix: str) -> str:
    for line in content.splitlines():
        head = line.split(":", 1)[0].split("：", 1)[0]
        if line.startswith(prefix) or prefix in head:
            if "：" in line:
                return line.split("：", 1)[1].strip()
            if ":" in line:
                return line.split(":", 1)[1].strip()
    return ""


def _bi(en: str, cn: str) -> str:
    return f"{en} / {cn}"


def _section_lines(content: str, section_title: str, limit: int) -> List[str]:
    lines = content.splitlines()
    start = -1
    for index, line in enumerate(lines):
        if section_title == line.strip() or section_title in line:
            start = index + 1
            break
    if start < 0:
        return []
    selected: List[str] = []
    for line in lines[start:]:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith(("I.", "II.", "III.", "IV.", "V.", "VI.", "VII.")):
            break
        selected.append(stripped)
        if len(selected) >= limit:
            break
    return selected


def build_report_notification_content(
    content: str,
    report_doc_url: str,
    text_report_doc_url: str = "",
    details_url: Optional[str] = None,
    draft: bool = False,
    feedback_deadline: str = "",
) -> str:
    title = "[Draft for Review / 草稿待确认] GBSS Weekly AI & Service Intelligence" if draft else "GBSS Weekly AI & Service Intelligence"
    period = _content_value(content, "Period") or _content_value(content, "周期") or "-"
    topic = _content_value(content, "Weekly Topic") or _content_value(content, "本周 Topic") or "-"
    question = _content_value(content, "Research Question") or _content_value(content, "Subtitle") or "Business Support | Contact Center AI | Voice AI | AIQC | OPC | Governance"
    summary_lines = _section_lines(content, "Executive Summary", 4)
    analysis_lines = _section_lines(content, "IV. Strategic Analysis", 3)

    lines = [
        f"### {title}",
        f"**Period / 周期**: {period}",
        "**Audience / 受众**: CEO & Direct Reports",
        f"**Weekly Topic / 本周 Topic**: {topic}",
        f"**Research Question / 核心问题**: {question}",
    ]
    if draft and feedback_deadline:
        lines.append(f"**Feedback Deadline / 反馈截止**: {feedback_deadline}")
    if report_doc_url:
        lines.extend(["", f"**Image Version / 图片版**: [Open one-page report]({report_doc_url})"])
    if text_report_doc_url:
        lines.append(f"**Text Version / 文字版**: [Open full analysis]({text_report_doc_url})")
    if details_url:
        lines.append(f"**News Records / News 明细**: [Open News table]({details_url})")

    if summary_lines:
        lines.extend(["", "#### CEO Summary / CEO 摘要"])
        lines.extend(summary_lines)
    if analysis_lines:
        lines.extend(["", "#### Management View / 管理层判断"])
        lines.extend(analysis_lines)

    lines.extend(["", "Full tables, source links, Next 4 Topics and research direction are archived in the report document."])
    lines.append("完整表格、来源链接、Next 4 Topics 和调研方向已沉淀在文档内。")
    return "\n".join(lines)


def build_image_report_notification_content(
    content: str,
    image_report_doc_url: str,
    draft: bool = False,
    feedback_deadline: str = "",
) -> str:
    title = "[Draft for Review / 草稿待确认] GBSS Weekly AI & Service Intelligence | Image Version / 图片版" if draft else "GBSS Weekly AI & Service Intelligence | Image Version / 图片版"
    period = _content_value(content, "Period") or _content_value(content, "周期") or "-"
    topic = _content_value(content, "Weekly Topic") or _content_value(content, "本周 Topic") or "-"
    lines = [
        f"### {title}",
        f"**Period / 周期**: {period}",
        f"**Weekly Topic / 本周 Topic**: {topic}",
    ]
    if draft and feedback_deadline:
        lines.append(f"**Feedback Deadline / 反馈截止**: {feedback_deadline}")
    lines.extend([
        "",
        f"[Open one-page image report / 打开一页式图片报告]({image_report_doc_url})",
    ])
    return "\n".join(lines)


def build_text_report_notification_content(
    content: str,
    text_report_doc_url: str,
    details_url: Optional[str] = None,
    draft: bool = False,
    feedback_deadline: str = "",
) -> str:
    title = "[Draft for Review / 草稿待确认] GBSS Weekly AI & Service Intelligence | Text Details / 文字版" if draft else "GBSS Weekly AI & Service Intelligence | Text Details / 文字版"
    period = _content_value(content, "Period") or _content_value(content, "周期") or "-"
    topic = _content_value(content, "Weekly Topic") or _content_value(content, "本周 Topic") or "-"
    question = _content_value(content, "Research Question") or _content_value(content, "Subtitle") or "Business Support | Contact Center AI | Voice AI | AIQC | OPC | Governance"
    summary_lines = _section_lines(content, "Executive Summary", 3)
    analysis_lines = _section_lines(content, "IV. Strategic Analysis", 3)
    lines = [
        f"### {title}",
        f"**Period / 周期**: {period}",
        f"**Weekly Topic / 本周 Topic**: {topic}",
        f"**Research Question / 核心问题**: {question}",
    ]
    if draft and feedback_deadline:
        lines.append(f"**Feedback Deadline / 反馈截止**: {feedback_deadline}")
    lines.extend(["", f"**Full Text Version / 完整文字版**: [Open full analysis]({text_report_doc_url})"])
    if details_url:
        lines.append(f"**News Records / News 明细**: [Open News table]({details_url})")
    if summary_lines:
        lines.extend(["", "#### CEO Summary / CEO 摘要"])
        lines.extend(summary_lines)
    if analysis_lines:
        lines.extend(["", "#### Management View / 管理层判断"])
        lines.extend(analysis_lines)
    return "\n".join(lines)


def entity_label(record: Dict[str, Any]) -> str:
    entities = [entity for entity in record_entities(record) if entity != "Other"]
    return ", ".join(entities) if entities else "Unclassified"


def change_type(record: Dict[str, Any]) -> str:
    fields = record.get("fields") or {}
    label = label_name(fields).lower()
    text = record_text(record)
    if label in {"funding", "m&a"} or any(hint in text for hint in FUNDING_HINTS):
        return "Capital / M&A"
    if label in {"earnings"} or is_metric_record(record):
        return "Scale / Performance"
    if any(word in text for word in ("launch", "product", "platform", "tool", "agent", "ai")):
        return "Product / Capability"
    if any(word in text for word in ("partner", "alliance", "collaboration", "integrat")):
        return "Partnership / Ecosystem"
    if any(word in text for word in ("regulation", "license", "compliance", "regulated")):
        return "Regulation / Compliance"
    return label_name(fields)


def strategic_implication(record: Dict[str, Any]) -> str:
    section = section_name(record)
    text = record_text(record)
    if section == "Contact Center":
        if any(word in text for word in ("secure", "regulated", "compliance", "fortanix", "nvidia")):
            return "Enterprise AI is moving toward secure, compliant and scalable deployment. / 企业级 AI 正从可用性走向安全、合规和规模化部署。"
        return "Voice and agentic AI are reshaping service interactions and operating efficiency. / Voice/Agentic AI 正在重塑服务交互和运营效率。"
    if any(word in text for word in ("agent", "programmable", "openai", "ai")):
        return "AI-agent scenarios are redefining payments and financial infrastructure. / AI agent 场景正在重定义支付和金融基础设施。"
    if any(word in text for word in ("global", "cross-border", "expand")):
        return "Cross-border and globalization capabilities keep expanding. / 跨境和全球化能力继续外溢。"
    if is_funding_record(record):
        return "Capital continues to price this capability direction. / 资本仍在为该能力方向定价。"
    return "Treat this as an industry weak signal for continued tracking. / 作为行业弱信号继续观察。"


def executive_priority(record: Dict[str, Any]) -> str:
    text = record_text(record)
    if any(word in text for word in ("visa", "openai", "stripe", "regulated", "nvidia", "deepgram")):
        return "P1"
    if is_funding_record(record) or is_metric_record(record):
        return "P1"
    return "P2"


def executive_summary_lines(records: List[Dict[str, Any]], entity_rows: List[Tuple[str, List[Dict[str, Any]]]]) -> List[str]:
    section_counts = Counter(section_name(record) for record in records)
    type_counts = Counter(change_type(record) for record in records)
    top_entities = [entity for entity, _ in entity_rows if entity != "Other"]
    dominant_types = ", ".join(f"{name} {count}" for name, count in type_counts.most_common(3)) or "none"
    lines = [
        f"1. This week includes {len(records)} accepted external signals: Finance {section_counts.get('Finance', 0)}, Contact Center {section_counts.get('Contact Center', 0)}. The main signal types are {dominant_types}.",
        f"1. 本周已采纳外部信号 {len(records)} 条：Finance {section_counts.get('Finance', 0)} 条，Contact Center {section_counts.get('Contact Center', 0)} 条；主要类型为 {dominant_types}。",
    ]
    if top_entities:
        lines.append(f"2. High-frequency benchmarks this week are {', '.join(top_entities[:5])}; they should be CEO-level watch items.")
        lines.append(f"2. 本周高频标杆为 {', '.join(top_entities[:5])}，建议作为 CEO 层关注对象。")
    else:
        lines.append("2. No single benchmark dominated this week, but several industry weak signals deserve continued tracking.")
        lines.append("2. 本周未形成单一主导标杆，但多个行业弱信号值得持续跟踪。")
    if any(section_name(record) == "Contact Center" for record in records):
        lines.append("3. Contact Center AI is moving toward enterprise-grade security, compliance and production deployment, with direct implications for GBSS service efficiency.")
        lines.append("3. Contact Center AI 正在向企业级安全、合规和生产部署演进，对 GBSS 服务效率有直接参考意义。")
    else:
        lines.append("3. The week remains skewed toward Finance/Payments; AI agents, cross-border expansion and new payment infrastructure may reshape business boundaries.")
        lines.append("3. 本周仍偏 Finance/Payments，AI agents、跨境扩张和新支付基础设施可能重塑业务边界。")
    return lines


def topic_fields(topic: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    if not topic:
        return {}
    if "fields" in topic and isinstance(topic.get("fields"), dict):
        return topic.get("fields") or {}
    return topic


def topic_value(topic: Optional[Dict[str, Any]], key: str, default: str = "-") -> str:
    return field_text(topic_fields(topic).get(key)) or default


def infer_topic_from_records(records: List[Dict[str, Any]]) -> Dict[str, str]:
    text = " ".join(record_text(record) for record in records)
    if "visa" in text or "openai" in text or "agent" in text or "programmable" in text:
        return {
            "Topic": "AI Agent Commerce and Programmable Payments",
            "Research Question": "How will AI agents change payment initiation, authorization, fraud control, and merchant/customer ownership?",
            "Why It Matters": "Agentic commerce may move transaction control from checkout pages into AI-driven decision flows.",
            "Scope": "Visa, OpenAI, Stripe, tokenization, agent identity, transaction controls.",
        }
    if "voice ai" in text or "deepgram" in text:
        return {
            "Topic": "Enterprise Voice AI in Regulated Operations",
            "Research Question": "What makes voice AI production-ready for regulated service operations?",
            "Why It Matters": "Voice AI is shifting from demo capability to secure, compliant enterprise deployment.",
            "Scope": "Deepgram, NVIDIA, Fortanix, contact center AI, compliance, on-prem deployment.",
        }
    return {
        "Topic": "GBSS Industry and Competitor Intelligence",
        "Research Question": "What changed this week, and what should GBSS learn from it?",
        "Why It Matters": "The weekly pulse converts external signals into management-level decisions and follow-up actions.",
        "Scope": "Accepted News records, competitor movements, market signals, strategic implications.",
    }


def build_competitor_report_content(
    records: List[Dict[str, Any]],
    range_label: str,
    details_url: Optional[str] = None,
    max_items_per_section: Optional[int] = None,
    draft: bool = False,
    research_topic: Optional[Dict[str, Any]] = None,
    next_topics: Optional[List[Dict[str, Any]]] = None,
    research_context: Optional[Dict[str, Any]] = None,
) -> str:
    topic = research_topic or infer_topic_from_records(records)
    topic_name = topic_value(topic, "Topic")
    if topic_name in {"GBSS Industry and Competitor Intelligence", "-"}:
        topic_name = "AI is reshaping Contact Center operating model and business support capability"
    selected_records = sorted_recent_records(records)
    if max_items_per_section:
        selected_records = selected_records[:max_items_per_section]
    report = build_report_data(selected_records or records, range_label, topic_name, research_context=research_context)
    summary = report["executiveSummary"]
    one_page = report["onePageBrief"]
    title = "[Draft for Review / 草稿待确认] GBSS Weekly AI & Service Intelligence" if draft else "GBSS Weekly AI & Service Intelligence"
    lines = [
        title,
        f"Period / 周期: {range_label}",
        "Audience / 受众: CEO & Direct Reports",
        "Subtitle / 副标题: Business Support | Contact Center AI | Voice AI | AIQC | OPC | Governance",
        "Positioning / 定位: External trend radar + GBSS business support analysis + Contact Center insight + action plan + deep dive + one-page brief",
        f"Weekly Topic / 本周 Topic: {summary['weeklyTopic']}",
        "",
    ]
    if draft:
        lines.extend([
            "Draft Note: Please provide feedback or adjust the News table before Sunday 12:00; the final version will be sent in CEO-ready format.",
            "草稿说明：请在周日12:00前完成反馈或调整 News 表；终稿将按 CEO-ready 版本发送。",
            "",
        ])

    if draft and details_url:
        lines.extend([f"Review Entry / 审核明细入口: [News Table]({details_url})", ""])

    priority_summary = summary.get("prioritySummary") or {}
    lines.extend(["1. Executive Summary / 本周关键结论与主题判断", ""])
    research_quality = report.get("researchQuality") or {}
    if research_quality:
        lines.append(f"Research Status / 研究状态：{research_quality.get('status', 'Signal Brief')}")
        blockers = research_quality.get("blockers") or []
        if blockers:
            lines.append(f"Evidence Gate / 证据门禁：{' ; '.join(str(item) for item in blockers)}")
    lines.append("One-sentence conclusion / 一句话结论：{}".format(summary["oneSentenceConclusion"]))
    lines.append("Management Takeaway：{}".format(summary["managementTakeaway"]))
    lines.append("Organization Insight：{}".format(summary["organizationInsight"]))
    lines.append("Contact Center Insight：{}".format(summary["contactCenterInsight"]))
    executive_takeaways = report.get("executiveTakeaways") or []
    if executive_takeaways:
        lines.extend(["", "Key Takeaways / 关键结论", ""])
        for index, item in enumerate(executive_takeaways, start=1):
            priority = item.get("priority", "Watch")
            lines.append(f"{index}. {priority} | {item.get('en', '-')}")
            lines.append(f"{index}. {priority} | {item.get('zh', '-')}")
    lines.extend(markdown_table(
        ["Metric / 指标", "Value / 数值"],
        [
            ["External Signals Tracked", summary["signalCount"]],
            ["Business Relevant Signals", summary["businessRelevantSignalCount"]],
            ["Contact Center Signals", summary["contactCenterSignalCount"]],
            ["OPC Model Signals", summary["opModelSignalCount"]],
            ["Priority Summary", "P0 {P0} / P0 Candidate {P0 Candidate} / P1 {P1} / P2 {P2} / Watch {Watch}".format(**priority_summary)],
        ],
    ))
    lines.extend(["", "Business Impact Highlights / 重点业务影响"])
    for item in summary["businessImpactHighlights"]:
        lines.append(f"- {item}")
    lines.extend(["", "GBSS Core Impacts / GBSS 核心影响"])
    for item in summary["gbssCoreImpacts"]:
        lines.append(f"- {item}")

    lines.extend(["", "2. External Signal Radar / 外部动态雷达", ""])
    radar_rows = []
    for item in report["signalRadar"]:
        radar_rows.append([
            item["domain"],
            item["signalCount"],
            "; ".join(item["representativeEvents"]),
            " / ".join(item["businessRelevance"]),
            "; ".join(item["gbssRelevantScenarios"]),
            item["strategicTheme"],
            item["priority"],
            truncate_text(item["initialJudgement"], 120),
        ])
    lines.extend(markdown_table(
        ["Domain / 领域", "Signals / 数量", "Representative Events / 代表事件", "Business Relevance", "GBSS Scenarios / GBSS 场景", "Strategic Theme", "Priority", "Initial Judgement / 初步判断"],
        radar_rows or [["-", 0, "-", "-", "-", "-", "Watch", "No accepted signal this week."]],
    ))

    lines.extend(["", "3. Priority News Cards / 本周重点动态卡片", ""])
    for index, card in enumerate(report["priorityNewsCards"], start=1):
        lines.extend([
            f"### {index}. {card['priority']} | {card['newsTitle']}",
            f"- Score / 评分：{card['score']}",
            f"- What happened / 发生了什么：{card['whatHappened']}",
            f"- Why it matters to GBSS / 为什么重要：{card['whyItMattersToGBSS']}",
            f"- Evidence / 证据：{card.get('evidenceId', '-') } | {card.get('sourceTier', '-') } | Confidence / 置信度：{card.get('confidence', '-')}",
            f"- Traceability / 追溯：Event {card.get('eventId') or '-'} | Event Source {card.get('eventSourceIds') or '-'} | Evidence {card.get('evidenceIds') or card.get('evidenceId') or '-'} | Claim {card.get('claimIds') or '-'}",
            f"- Publish Date / 发布时间：{card.get('publishDate') or '-'}",
            f"- Business Relevance：{' / '.join(card['businessRelevance'])}",
            f"- Strategic Theme：{card['strategicTheme']}",
            f"- Impacted Capability：{' / '.join(card['impactedCapability'])}",
            f"- Efficiency Opportunity / 效率机会：{card['efficiencyOpportunity']}",
            f"- Operating Model Implication / 组织模式影响：{card['operatingModelImplication']}",
            f"- Suggested Action / 建议动作：{card['suggestedAction']}",
            f"- Owner / 负责人：{card['suggestedOwner']}",
            f"- Timeline / 时间：{card['timeline']}",
            f"- Source / 来源：{card['source']}",
            "",
        ])

    lines.extend(["4. GBSS Impact Analysis / GBSS 影响分析", ""])
    impact_rows = []
    for item in report["impactAnalysis"]:
        impact_rows.append([
            item["strategicTheme"],
            item["externalTrend"],
            item["businessImpact"],
            item["operatingModelImpact"],
            item["efficiencyImpact"],
            item["currentJudgement"],
            item["suggestedAction"],
        ])
    lines.extend(markdown_table(
        ["Strategic Theme / 战略主线", "External Trend / 外部趋势", "Business Impact / 当前重点业务影响", "Org / OPC Impact / 组织与OPC影响", "Efficiency Impact / 效率项目影响", "Judgement / 判断", "Suggested Action / 建议动作"],
        impact_rows,
    ))

    lines.extend(["", "5. Watchlist & Deep Dive / 下周观察与深度分析", ""])
    action_rows = []
    for item in report["actions"]:
        action_rows.append([
            item["priority"],
            item["action"],
            " / ".join(item["businessRelevance"]),
            item["strategicTheme"],
            item["owner"],
            item["timeline"],
            item["expectedOutput"],
            item["status"],
        ])
    if action_rows:
        lines.extend(["A. This Week Actions / 本周建议动作", ""])
        lines.extend(markdown_table(["Priority", "Action / 动作", "Business / 对应业务", "Strategic Theme", "Owner", "Timeline", "Expected Output", "Status"], action_rows))

    lines.extend(["", "B. Next Week Watchlist / 下周 Watchlist", ""])
    watch_rows = []
    for item in report["watchlist"]:
        watch_rows.append([
            item["topic"],
            item["focus"],
            " / ".join(item["businessRelevance"]),
            item["strategicTheme"],
            item["whyItMatters"],
            item["triggerCondition"],
        ])
    lines.extend(markdown_table(["Topic / 观察主题", "Focus / 关注点", "Business / 关联业务", "Strategic Theme", "Why It Matters / 为什么重要", "Trigger / 触发行动条件"], watch_rows))

    deep = report["deepDive"]
    lines.extend(["", "C. Weekly Deep Dive / 本周深度分析", ""])
    lines.append(f"Deep Dive Topic / 深度分析主题：{deep['topic']}")
    if deep.get("phrases"):
        lines.append("Deep Insight Phrases / 深度洞察短语：")
        for phrase in deep["phrases"]:
            lines.append(f"- {phrase}")
    if deep.get("researchSynthesis"):
        lines.extend(["", "OpenAI Deep Research Synthesis / OpenAI 深度研究综合：", deep["researchSynthesis"]])
    lines.append(f"Related Business Priority / 关联业务优先级：{' / '.join(deep['relatedBusinessPriority'])}")
    lines.append(f"Related Strategic Theme / 关联战略主线：{' / '.join(deep['relatedStrategicTheme'])}")
    lines.append(f"Background / 背景：{deep['background']}")
    lines.append("")
    lines.append("External Signals / 外部信号：")
    for item in deep["externalSignals"]:
        lines.append(f"- {item}")
    lines.append(f"Why It Matters to GBSS / 为什么对 GBSS 重要：{deep['whyItMattersToGBSS']}")
    lines.append("Impact on Current Strategy / 对当前战略方向影响：")
    for item in deep["impactOnCurrentStrategy"]:
        lines.append(f"- {item['area']}: {item['impact']}")
    lines.append(f"Internal Efficiency Link / 内部效率项目关系：{deep['internalEfficiencyLink']}")
    lines.append(f"Operating Model Implication / 组织与OPC影响：{deep['operatingModelImplication']}")
    lines.append("Key Risks / 关键风险：")
    for item in deep["keyRisks"]:
        lines.append(f"- {item}")
    lines.append("Opportunities / 机会点：")
    for item in deep["opportunities"]:
        lines.append(f"- {item}")
    lines.append("Recommended Actions / 建议动作：")
    for item in deep["recommendedActions"]:
        lines.append(f"- {item}")
    lines.append(f"30-Day Next Step / 未来30天推进事项：{deep['next30DayStep']}")
    lines.append(f"Management Takeaway / 管理层一句话结论：{deep['managementTakeaway']}")

    lines.extend(["", "One-page Brief Source / 一页简版摘要来源"])
    lines.append(f"- Title: {one_page['title']}")
    lines.append(f"- Weekly Deep Insight: {one_page['weeklyDeepInsight']['insight']}")

    lines.extend([
        "",
        "--------------------------",
        EXECUTIVE_NOTE,
    ])
    return "\n".join(lines)


def build_headlines_content(
    records: List[Dict[str, Any]],
    cadence: str,
    range_label: str,
    details_url: Optional[str] = None,
    max_items_per_section: Optional[int] = None,
) -> str:
    rocket = "\U0001f680"
    bullet = "\u2022"
    title = "Finance & Contact Center Daily Report" if cadence.lower() == "daily" else f"Finance & Contact Center {cadence} Headlines"
    lines = [title]
    for section in ordered_sections(records):
        section_records = sorted([
            record for record in records
            if section_name(record) == section
        ], key=record_sort_key)
        if max_items_per_section:
            section_records = section_records[:max_items_per_section]
        if not section_records:
            continue
        lines.extend(["", f"[{rocket}] {SECTION_TITLES.get(section, section)}", ""])
        for record in section_records:
            fields = record.get("fields") or {}
            url = source_url(fields)
            headline = concise_headline(fields.get("Title") or fields.get("Title & URL") or "-")
            label = fields.get("Label") or fields.get("Tag") or "News"
            source = f" ([{source_domain(url)}]({url}))" if url else ""
            lines.append(f"{bullet}  {label}: {headline}{source}  ")
            publish_date = field_text(fields.get("Publish Date")) or "-"
            lines.append(f"   Publish Date: {publish_date}  ")
            event_id = field_text(fields.get("Event ID"))
            if event_id and cadence.lower() != "daily":
                event_sources = field_text(fields.get("Event Source IDs")) or "-"
                evidence_ids = field_text(fields.get("Evidence IDs")) or "-"
                claim_ids = field_text(fields.get("Claim IDs")) or "-"
                lines.append(
                    f"   ↳ Event {event_id} | Event Source {event_sources} | "
                    f"Evidence {evidence_ids} | Claim {claim_ids}  "
                )
    includes_deadline_fallback = any(
        "AI_Deadline" in field_text((record.get("fields") or {}).get("Review Decision Sources"))
        for record in records
    )
    lines.extend(["", "--------------------------", AI_DEADLINE_NOTE if includes_deadline_fallback else NOTE])
    return "\n".join(lines)


def build_weekly_research_link_content(
    records: List[Dict[str, Any]],
    range_label: str,
    research_topic: str,
    research_document_url: str,
    max_items_per_section: Optional[int] = None,
) -> str:
    if not str(research_document_url or "").startswith(("https://", "http://")):
        raise ValueError("a valid Research Document URL is required")
    digest_records = [
        {
            **record,
            "fields": {
                key: value for key, value in (record.get("fields") or {}).items()
                if key not in {"Event ID", "Event Source IDs", "Evidence IDs", "Claim IDs"}
            },
        }
        for record in records
    ]
    digest = build_headlines_content(digest_records, "Weekly", range_label, max_items_per_section=max_items_per_section)
    digest_lines = digest.splitlines()
    if digest_lines:
        digest_lines = digest_lines[1:]
    return "\n".join([
        "GBSS Weekly AI & Service Intelligence",
        "",
        f"Period: {range_label}",
        f"Research Focus: {research_topic or 'GBSS Weekly Deep Research'}",
        f"Deep Research Report: [Open DingTalk document]({research_document_url})",
        "",
        "Weekly Key Events & News",
        *digest_lines,
    ])


def build_empty_daily_report_content(report_date: str) -> str:
    return "\n".join([
        "Finance & Contact Center Daily Report",
        "",
        "No newly accepted external events today.",
        f"Report Date: {report_date}",
        "",
        "The scheduled review and publication checks completed successfully.",
    ])
