"""Validate and import a structured Deep Research synthesis into Claim Ledger."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.audit_trail import AuditTrailWriter  # noqa: E402
from app.research_production import ensure_research_production_sheets, import_synthesis_claims, load_research_context, load_synthesis_payload  # noqa: E402
from app.run_logs import RunLogStore  # noqa: E402
from app.secrets import SecretStore  # noqa: E402
from app.storage import SettingsStore  # noqa: E402


DATA = ROOT / "data"
parser = argparse.ArgumentParser()
parser.add_argument("payload", help="JSON generated by the approved Deep Research synthesis contract")
parser.add_argument("--research-id", required=True)
args = parser.parse_args()

store = SettingsStore(DATA / "settings.sqlite3", SecretStore(DATA / "secrets.json"))
run_logs = RunLogStore(DATA / "settings.sqlite3")
settings = store.load(masked=False)
audit = AuditTrailWriter(settings, store)
run_id = run_logs.start("import_deep_research_synthesis", provider="structured_json")

try:
    tables = ensure_research_production_sheets(settings, store)
    context = load_research_context(settings, tables, args.research_id)
    payload = load_synthesis_payload(args.payload)
    saved = import_synthesis_claims(settings, tables.claims, args.research_id, payload, context["evidence"])
    refreshed = load_research_context(settings, tables, args.research_id)
    audit.record(
        run_id=run_id, workflow="import_deep_research_synthesis", stage_code="RESEARCH.import_claims", stage_name="Import Deep Research claims",
        status="success", input_summary=args.payload, output_summary=f"Imported {len(saved)} claims; quality={refreshed['quality']['status']}.",
        result_count=len(saved), report_id=args.research_id, related_sheet=tables.claims.sheet_id, metadata=refreshed["quality"],
    )
    run_logs.finish(run_id, "success", result_count=len(saved), message=f"imported {len(saved)} claims", metadata=refreshed["quality"])
    print(f"import_deep_research_synthesis success: claims={len(saved)}; quality={refreshed['quality']['status']}")
except Exception as exc:
    run_logs.finish(run_id, "failed", message="deep research synthesis import failed", error=str(exc))
    audit.record(run_id=run_id, workflow="import_deep_research_synthesis", stage_code="RESEARCH.import_claims", stage_name="Import Deep Research claims", status="failed", error=str(exc), report_id=args.research_id)
    raise
